http:
  middlewares:
    redirect-http-www:
      redirectRegex:
        regex: "^http?://www\\.(.+)"
        replacement: "http://${1}"
        permanent: true
    redirect-https-www:
      redirectRegex:
        regex: "^https?://www\\.(.+)"
        replacement: "https://${1}"
        permanent: true
