services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      #- "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=rozy.firmansyah@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--providers.file.directory=/traefik/traefik.d"
    restart: always
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "./traefik.d:/traefik/traefik.d"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  rozy.dev:
    image: "rozy97/rozy.dev:v1.1.0"
    deploy:
      mode: replicated
      replicas: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rozy.dev.rule=Host(`rozy.dev`) || Host(`www.rozy.dev`)"
      - "traefik.http.routers.rozy.dev.entrypoints=websecure"
      - "traefik.http.routers.rozy.dev.tls.certresolver=myresolver"
      - "traefik.http.routers.rozy.dev.middlewares=redirect-http-www@file,redirect-https-www@file"

  adisarana.id:
    image: "rozy97/adisarana.id:v0.0.1"
    deploy:
      mode: replicated
      replicas: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adisarana.id.rule=Host(`adisarana.id`) || Host(`www.adisarana.id`)"
      - "traefik.http.routers.adisarana.id.entrypoints=websecure"
      - "traefik.http.routers.adisarana.id.tls.certresolver=myresolver"
      - "traefik.http.routers.adisarana.id.middlewares=redirect-http-www@file,redirect-https-www@file"
