services:
  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      #- "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=rozy.firmansyah@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver2.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver2.acme.email=rozy.firmansyah@gmail.com"
      - "--certificatesresolvers.myresolver2.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver3.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver3.acme.email=rozy.firmansyah@gmail.com"
      - "--certificatesresolvers.myresolver3.acme.storage=/letsencrypt/acme.json"
      - "--providers.file.directory=/traefik/traefik.d"
    restart: always
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "./traefik.d:/traefik/traefik.d"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - trf

  rozy_dev:
    image: "rozy97/rozy.dev:v1.1.0"
    deploy:
      mode: replicated
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rozy_dev.rule=Host(`rozy.dev`) || Host(`www.rozy.dev`)"
      - "traefik.http.routers.rozy_dev.entrypoints=websecure"
      - "traefik.http.routers.rozy_dev.tls.certresolver=myresolver"
      - "traefik.http.routers.rozy_dev.middlewares=redirect-http-www@file,redirect-https-www@file"
    networks:
      - trf

  smartmining:
    image: "rozy97/smartmining:v0.0.8"
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smartmining.rule=Host(`api.malili.adisarana.id`)"
      - "traefik.http.routers.smartmining.entrypoints=websecure"
      - "traefik.http.routers.smartmining.tls.certresolver=myresolver3"
    networks:
      - trf

  adisarana_id:
    image: "rozy97/adisarana.id:v0.0.14"
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adisarana_id.rule=Host(`malili.adisarana.id`)"
      - "traefik.http.routers.adisarana_id.entrypoints=websecure"
      - "traefik.http.routers.adisarana_id.tls.certresolver=myresolver2"
      - "traefik.http.routers.adisarana_id.middlewares=redirect-http-www@file,redirect-https-www@file"
    networks:
      - trf

networks:
  trf:
    driver: bridge
